### ISSUE TITLE
Failed resolution of: Ldmax/dialog/R$style;

### ISSUE THREAD

**Issue by magtimmermans** [FANMixco/SpotsDialog.Xamarin#1]
Hi,

When using this, I get this error: Failed resolution of: Ldmax/dialog/R$style;

**Comment by FANMixco** [comment]
Hi @magtimmermans can you provide me the example? Because it's quite open question. Thanks.

**Comment by magtimmermans** [comment]
Seems that this was a problem of Xamarin. I have deleted the bin directory and rebuild everything and the error was gone.
